name: novnc
base: core18 # the base snap is the execution environment for this snap
version: '1.1.0'
summary: Open Source VNC client using HTML5 (WebSockets, Canvas)
description: |
  Open Source VNC client using HTML5 (WebSockets, Canvas).
  noVNC is both a VNC client JavaScript library as well as an application built on top of that library. noVNC runs well in any modern browser including mobile browsers (iOS and Android).

grade: stable
confinement: strict

parts:
    novnc:
        source: https://github.com/tkedwards/noVNC.git # https://github.com/novnc/noVNC/archive/v$SNAPCRAFT_PROJECT_VERSION.tar.gz
        plugin: dump
        stage-packages:
            - websockify
apps:
    novnc:
        command: utils/launch.sh
        plugs: [network, network-bind]
    n5900:
        command: utils/launch.sh --vnc localhost:5900 --listen 6080
        daemon: simple
        plugs: [network, network-bind]
    n5901:
        command: utils/launch.sh --vnc localhost:5901 --listen 6081
        daemon: simple
        plugs: [network, network-bind]
    n5902:
        command: utils/launch.sh --vnc localhost:5902 --listen 6082
        daemon: simple
        plugs: [network, network-bind]
    n5903:
        command: utils/launch.sh --vnc localhost:5903 --listen 6083
        daemon: simple
        plugs: [network, network-bind]
    n5904:
        command: utils/launch.sh --vnc localhost:5904 --listen 6084
        daemon: simple
        plugs: [network, network-bind]
    n5905:
        command: utils/launch.sh --vnc localhost:5905 --listen 6085
        daemon: simple
        plugs: [network, network-bind]
